services:
  - type: web
    name: scrumlyn-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JIRA_CLIENT_ID
        sync: false
      - key: JIRA_CLIENT_SECRET
        sync: false
      - key: JIRA_REDIRECT_URI
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASS
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: APP_NAME
        value: Scrumlyn
